# Generated by Django 5.0.3 on 2024-03-31 04:33

import birthday.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shakha_dayitva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'सोसायटी',
                'verbose_name_plural': 'सोसायटी',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Swayamsevak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=15)),
                ('middle_Name', models.CharField(max_length=15)),
                ('last_Name', models.CharField(max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('date_of_birth_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('date_of_birth', birthday.fields.BirthdayField()),
                ('house_Flat_No', models.CharField(max_length=20, verbose_name='House/Flat No')),
                ('ganavesh', models.CharField(blank=True, default='', max_length=100)),
                ('shiksha_Varg', models.CharField(blank=True, choices=[('Prarambhik', 'Prarambhik'), ('Prathamik', 'Prathamik'), ('Pratham', 'Pratham'), ('Dvitiya', 'Dvitiya'), ('Tritiya', 'Tritiya')], default='', max_length=12)),
                ('ghosh_Vadya', models.CharField(blank=True, default='', max_length=100)),
                ('dayitva', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shakha_dayitva.model')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='guru_govind_singh.society')),
            ],
            options={
                'verbose_name': 'स्वयंसेवक',
                'verbose_name_plural': 'शाखा पट',
                'abstract': False,
            },
        ),
    ]
