# Generated by Django 5.0.3 on 2024-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shakha_Dayitva', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'शाखा दायित्व',
                'verbose_name_plural': 'शाखा दायित्व',
            },
        ),
    ]
